---
title: "involved fatherhood"
author: "Cai, Yun-Ting"
date: "2019/8/28"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dpi = 300, warning = FALSE)
# prep --------------------------------------------------------------------
rm(list = ls())
cat("\014")
# packages
library(tidyverse)
# functions
source("C:/Users/user/Documents/Github_CFRC/TwinCity/AOV_auto.R")
source("C:/Users/user/Documents/Github_CFRC/TwinCity/t_auto.R")
# read data file ----------------------------------------------------------
load("D:/R_wd/Twin Cities/working/Taipei_all_tmp.RData")
```

### 兒童行為
#### [1] 比較主要照顧者（Ft9）
```{r CH_caregivers, echo=FALSE}

# [1] (Ch4) compare between caregivers ------------------------------------

# data
d.care <- df %>% 
        # care givers are both, the father and the mother
        filter(Ft9 %in% c(1, 2, 3)) %>% 
        # respondants are the father and the mother
        filter(Bd21 %in% c(1, 2)) %>% 
        # marital status: married
        filter(Bd30 == 1)

# 1. aggressive -----------------------------------------------------------

aov_auto(data = d.care, var1 = "Ch4_aggressive_sum", group = "Ft9")

# 2. soc ------------------------------------------------------------------

aov_auto(data = d.care, var1 = "Ch4_soc_sum", group = "Ft9")

# 3. attention ------------------------------------------------------------

aov_auto(data = d.care, var1 = "Ch4_attention_sum", group = "Ft9")

# 4. withdrawal -----------------------------------------------------------

aov_auto(data = d.care, var1 = "Ch4_withdrawal_sum", group = "Ft9")

```

#### [2] 控制「父母」為主要照顧者（Ft9 = 1），比較填答者（Bd21 = 1 or 2）
```{r caregivers_both, echo=FALSE}

# [2] (Ch4) compare within co-parenting -----------------------------------

# data
d.co <- df %>% 
        # caregivers are both
        filter(Ft9 == 1) %>% 
        # respondants are mother(1) and father(2)
        filter(Bd21 %in% c(1, 2)) %>% 
        # marital status: married
        filter(Bd30 == 1)

# group size
# d.co %>% group_by(Bd21) %>% group_size()

# 1. agg ------------------------------------------------------------------

t_auto(data = d.co, 
       var = "Ch4_aggressive_sum", 
       group = "Bd21", 
       alternative = "less")

# effect size
effsize::cohen.d(as.numeric(Ch4_aggressive_sum) ~ as.factor(Bd21), 
                 data = d.co,
                 pooled = TRUE, 
                 na.rm = TRUE, 
                 paired = FALSE, 
                 hedges.correction = F)

# 2. soc ------------------------------------------------------------------

t_auto(data = d.co,
       var = "Ch4_soc_sum", 
       group = "Bd21", 
       alternative = "less")

# effect size
effsize::cohen.d(as.numeric(Ch4_soc_sum) ~ Bd21, 
                 data = d.co,
                 pooled = TRUE, 
                 na.rm = TRUE, 
                 paired = FALSE)

# 3. attention ------------------------------------------------------------

t_auto(data = d.co,
       var = "Ch4_attention_sum", 
       group = "Bd21", 
       alternative = "less")

# effect size
effsize::cohen.d(as.integer(Ch4_attention_sum) ~ Bd21, 
                 data = d.co,
                 na.rm = TRUE, 
                 paired = FALSE)

# 4. withdrawal -----------------------------------------------------------

t_auto(data = d.co,
       var = "Ch4_withdrawal_sum", 
       group = "Bd21", 
       alternative = "less")

# effect size
effsize::cohen.d(as.integer(Ch4_withdrawal_sum) ~ Bd21, 
                 data = d.co,
                 na.rm = TRUE, 
                 paired = FALSE)

```

#### [3] 控制填答者母親，比較主要照顧者為父母、母親（Bd21 = 1）
```{r respondant_mother, echo=FALSE}
# [3] (Ch4) compare both with the mother (within the mother) --------------

# data
d.co.m <- df %>% 
        # caregivers are both and the mother
        filter(Ft9 %in% c(1, 3)) %>% 
        # respondant is the mother
        filter(Bd21 == 1) %>% 
        # marital status: married
        filter(Bd30 == 1)

# 1. agg ------------------------------------------------------------------
t_auto(data = d.co.m, 
       var = "Ch4_aggressive_sum", 
       group = "Ft9", 
       alternative = "less")

# effect size
effsize::cohen.d(as.numeric(Ch4_aggressive_sum) ~ Ft9, 
                 data = d.co.m,
                 pooled = TRUE, 
                 na.rm = TRUE, 
                 paired = FALSE)

# 2. soc ------------------------------------------------------------------
t_auto(data = d.co.m, 
       var = "Ch4_soc_sum", 
       group = "Ft9", 
       alternative = "less")
# effect size
effsize::cohen.d(as.numeric(Ch4_soc_sum) ~ Ft9, 
                 data = d.co.m,
                 pooled = TRUE, 
                 na.rm = TRUE, 
                 paired = FALSE)

# 3. attention ------------------------------------------------------------
t_auto(data = d.co.m, 
       var = "Ch4_attention_sum", 
       group = "Ft9", 
       alternative = "less")

# effect size
effsize::cohen.d(as.numeric(Ch4_attention_sum) ~ Ft9, 
                 data = d.co.m,
                 pooled = TRUE, 
                 na.rm = TRUE, 
                 paired = FALSE)

# 4. withdrawal -----------------------------------------------------------
t_auto(data = d.co.m, 
       var = "Ch4_withdrawal_sum", 
       group = "Ft9", 
       alternative = "less")
# effect size
effsize::cohen.d(as.numeric(Ch4_withdrawal_sum) ~ Ft9, 
                 data = d.co.m,
                 pooled = TRUE, 
                 na.rm = TRUE, 
                 paired = FALSE)

```

### 社會支持
#### [1] 比較主要照顧者（Ft9）
```{r Sup_caregivers, echo=FALSE}

# [5] Bd43 ----------------------------------------------------------------
# 1. compare between caregivers -------------------------------------------

# 1 > 3 > 2 (both > the mother > the father)
aov_auto(data = d.care, 
         var1 = "Bd43_sum", 
         group = "Ft9")

```

#### [2] 雙因子變異數分析：主要照顧者 x 社會支持
```{r twoWay_CarexSup, echo=FALSE}
# [6] test interaction (Ft9 * Bd43) ---------------------------------------

d.care <- d.care
# group social support
d.care.soc <- d.care %>% 
        mutate(Bd43_G = case_when(Bd43_sum >= 6 & Bd43_sum < 13 ~ 1, 
                                  Bd43_sum >= 13 & Bd43_sum <= 18 ~ 2)) %>%  
        # as.factor
        mutate_at(vars(matches("Bd43_G")), as.factor)

# 1. agg ------------------------------------------------------------------

# shows no interaction
aov(Ch4_aggressive_sum ~ Ft9 * Bd43_G, data = d.care.soc) %>% summary()
# type 1 (seqrencial)
aov(Ch4_aggressive_sum ~ Ft9 + Bd43_G, data = d.care.soc) %>% summary()
# type 2
car::Anova(aov(Ch4_aggressive_sum ~ Ft9 + Bd43_G, data = d.care.soc), 
           type = "II")

# 2. soc ------------------------------------------------------------------

aov(Ch4_soc_sum ~ Ft9 * Bd43_G, data = d.care.soc) %>% summary()
# type 1 (seqrencial)
aov(Ch4_soc_sum ~ Ft9 + Bd43_G, data = d.care.soc) %>% summary()
# type 2
car::Anova(aov(Ch4_soc_sum ~ Ft9 + Bd43_G, data = d.care.soc), 
           type = "II")

# 3. attentioni -----------------------------------------------------------

aov(Ch4_attention_sum ~ Ft9 * Bd43_G, data = d.care.soc) %>% summary()
# type 1 (seqrencial)
aov(Ch4_attention_sum ~ Ft9 + Bd43_G, data = d.care.soc) %>% summary()
# type 2
car::Anova(aov(Ch4_attention_sum ~ Ft9 + Bd43_G, data = d.care.soc), 
           type = "II")

# 4. withdrawal -----------------------------------------------------------

aov(Ch4_withdrawal_sum ~ Ft9 * Bd43_G, data = d.care.soc) %>% summary()
# type 1 (seqrencial)
aov(Ch4_withdrawal_sum ~ Ft9 + Bd43_G, data = d.care.soc) %>% summary()
# type 2
car::Anova(aov(Ch4_withdrawal_sum ~ Ft9 + Bd43_G, data = d.care.soc), 
           type = "II")

```

#### [3] 控制社會支持程度（Bd43_G = 1 or 2）
```{r control_SUP, echo=FALSE}

# [*] control variable Bd43 -----------------------------------------------

# 1. high -----------------------------------------------------------------
d.care.43 <- d.care.soc %>% 
        filter(Bd43_G == 2)
aov_auto(data = d.care.43, var1 = "Ch4_aggressive_sum", group = "Ft9")
aov_auto(data = d.care.43, var1 = "Ch4_soc_sum", group = "Ft9")
aov_auto(data = d.care.43, var1 = "Ch4_attention_sum", group = "Ft9")
aov_auto(data = d.care.43, var1 = "Ch4_withdrawal_sum", group = "Ft9")


# 2. medium ---------------------------------------------------------------
d.care.43 <- d.care.soc %>% 
        filter(Bd43_G == 1)
aov_auto(data = d.care.43, var1 = "Ch4_aggressive_sum", group = "Ft9")
aov_auto(data = d.care.43, var1 = "Ch4_soc_sum", group = "Ft9")
aov_auto(data = d.care.43, var1 = "Ch4_attention_sum", group = "Ft9")
aov_auto(data = d.care.43, var1 = "Ch4_withdrawal_sum", group = "Ft9")

# # 3. low ------------------------------------------------------------------
# d.care.43 <- d.care.soc %>% 
#         filter(Bd43_G == 1)
# aov_auto(data = d.care.43, var1 = "Ch4_aggressive_sum", group = "Ft9")
# aov_auto(data = d.care.43, var1 = "Ch4_soc_sum", group = "Ft9")
# aov_auto(data = d.care.43, var1 = "Ch4_attention_sum", group = "Ft9")
# aov_auto(data = d.care.43, var1 = "Ch4_withdrawal_sum", group = "Ft9")

```

##### 